/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BibleBookmark {
  'bookName' : string,
  'verseNumber' : bigint,
  'chapterNumber' : bigint,
  'timestamp' : Time,
  'verseText' : string,
}
export type BibleTranslation = { 'esv' : null } |
  { 'kjv' : null } |
  { 'niv' : null };
export interface CheckIn {
  'mood' : MoodLabel,
  'note' : [] | [string],
  'timestamp' : Time,
}
export type MoodLabel = { 'sad' : null } |
  { 'hopeful' : null } |
  { 'anxious' : null } |
  { 'grateful' : null } |
  { 'stressed' : null };
export type Order = { 'less' : null } |
  { 'equal' : null } |
  { 'greater' : null };
export interface SavedPrayer {
  'prayerId' : string,
  'prayerTitle' : string,
  'savedAt' : Time,
  'category' : string,
}
export type Time = bigint;
export interface UserPreferences {
  'notificationsEnabled' : boolean,
  'displayName' : string,
  'preferredTranslation' : BibleTranslation,
}
export interface _SERVICE {
  'addBookmark' : ActorMethod<[string, bigint, bigint, string], undefined>,
  'addCheckIn' : ActorMethod<[MoodLabel, [] | [string]], undefined>,
  'compareByTime' : ActorMethod<[bigint, bigint], Order>,
  'compareText' : ActorMethod<[string, string], Order>,
  'compareTime' : ActorMethod<[bigint, bigint], Order>,
  'getBookmarks' : ActorMethod<[], Array<BibleBookmark>>,
  'getCheckInHistory' : ActorMethod<[], Array<CheckIn>>,
  'getLatestCheckIn' : ActorMethod<[], [] | [CheckIn]>,
  'getPreferences' : ActorMethod<[], UserPreferences>,
  'getSavedPrayers' : ActorMethod<[], Array<SavedPrayer>>,
  'removeBookmark' : ActorMethod<[string, bigint, bigint], undefined>,
  'removeSavedPrayer' : ActorMethod<[string], undefined>,
  'savePrayer' : ActorMethod<[string, string, string], undefined>,
  'updatePreferences' : ActorMethod<
    [BibleTranslation, boolean, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];