/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MoodLabel = IDL.Variant({
  'sad' : IDL.Null,
  'hopeful' : IDL.Null,
  'anxious' : IDL.Null,
  'grateful' : IDL.Null,
  'stressed' : IDL.Null,
});
export const Order = IDL.Variant({
  'less' : IDL.Null,
  'equal' : IDL.Null,
  'greater' : IDL.Null,
});
export const Time = IDL.Int;
export const BibleBookmark = IDL.Record({
  'bookName' : IDL.Text,
  'verseNumber' : IDL.Nat,
  'chapterNumber' : IDL.Nat,
  'timestamp' : Time,
  'verseText' : IDL.Text,
});
export const CheckIn = IDL.Record({
  'mood' : MoodLabel,
  'note' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
});
export const BibleTranslation = IDL.Variant({
  'esv' : IDL.Null,
  'kjv' : IDL.Null,
  'niv' : IDL.Null,
});
export const UserPreferences = IDL.Record({
  'notificationsEnabled' : IDL.Bool,
  'displayName' : IDL.Text,
  'preferredTranslation' : BibleTranslation,
});
export const SavedPrayer = IDL.Record({
  'prayerId' : IDL.Text,
  'prayerTitle' : IDL.Text,
  'savedAt' : Time,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBookmark' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'addCheckIn' : IDL.Func([MoodLabel, IDL.Opt(IDL.Text)], [], []),
  'compareByTime' : IDL.Func([IDL.Int, IDL.Int], [Order], ['query']),
  'compareText' : IDL.Func([IDL.Text, IDL.Text], [Order], ['query']),
  'compareTime' : IDL.Func([IDL.Int, IDL.Int], [Order], ['query']),
  'getBookmarks' : IDL.Func([], [IDL.Vec(BibleBookmark)], ['query']),
  'getCheckInHistory' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
  'getLatestCheckIn' : IDL.Func([], [IDL.Opt(CheckIn)], ['query']),
  'getPreferences' : IDL.Func([], [UserPreferences], ['query']),
  'getSavedPrayers' : IDL.Func([], [IDL.Vec(SavedPrayer)], ['query']),
  'removeBookmark' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'removeSavedPrayer' : IDL.Func([IDL.Text], [], []),
  'savePrayer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updatePreferences' : IDL.Func(
      [BibleTranslation, IDL.Bool, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MoodLabel = IDL.Variant({
    'sad' : IDL.Null,
    'hopeful' : IDL.Null,
    'anxious' : IDL.Null,
    'grateful' : IDL.Null,
    'stressed' : IDL.Null,
  });
  const Order = IDL.Variant({
    'less' : IDL.Null,
    'equal' : IDL.Null,
    'greater' : IDL.Null,
  });
  const Time = IDL.Int;
  const BibleBookmark = IDL.Record({
    'bookName' : IDL.Text,
    'verseNumber' : IDL.Nat,
    'chapterNumber' : IDL.Nat,
    'timestamp' : Time,
    'verseText' : IDL.Text,
  });
  const CheckIn = IDL.Record({
    'mood' : MoodLabel,
    'note' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
  });
  const BibleTranslation = IDL.Variant({
    'esv' : IDL.Null,
    'kjv' : IDL.Null,
    'niv' : IDL.Null,
  });
  const UserPreferences = IDL.Record({
    'notificationsEnabled' : IDL.Bool,
    'displayName' : IDL.Text,
    'preferredTranslation' : BibleTranslation,
  });
  const SavedPrayer = IDL.Record({
    'prayerId' : IDL.Text,
    'prayerTitle' : IDL.Text,
    'savedAt' : Time,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addBookmark' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'addCheckIn' : IDL.Func([MoodLabel, IDL.Opt(IDL.Text)], [], []),
    'compareByTime' : IDL.Func([IDL.Int, IDL.Int], [Order], ['query']),
    'compareText' : IDL.Func([IDL.Text, IDL.Text], [Order], ['query']),
    'compareTime' : IDL.Func([IDL.Int, IDL.Int], [Order], ['query']),
    'getBookmarks' : IDL.Func([], [IDL.Vec(BibleBookmark)], ['query']),
    'getCheckInHistory' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
    'getLatestCheckIn' : IDL.Func([], [IDL.Opt(CheckIn)], ['query']),
    'getPreferences' : IDL.Func([], [UserPreferences], ['query']),
    'getSavedPrayers' : IDL.Func([], [IDL.Vec(SavedPrayer)], ['query']),
    'removeBookmark' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'removeSavedPrayer' : IDL.Func([IDL.Text], [], []),
    'savePrayer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updatePreferences' : IDL.Func(
        [BibleTranslation, IDL.Bool, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };