/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CheckIn {
    mood: MoodLabel;
    note?: string;
    timestamp: Time;
}
export interface UserPreferences {
    notificationsEnabled: boolean;
    displayName: string;
    preferredTranslation: BibleTranslation;
}
export type Time = bigint;
export interface BibleBookmark {
    bookName: string;
    verseNumber: bigint;
    chapterNumber: bigint;
    timestamp: Time;
    verseText: string;
}
export interface SavedPrayer {
    prayerId: string;
    prayerTitle: string;
    savedAt: Time;
    category: string;
}
export enum BibleTranslation {
    esv = "esv",
    kjv = "kjv",
    niv = "niv"
}
export enum MoodLabel {
    sad = "sad",
    hopeful = "hopeful",
    anxious = "anxious",
    grateful = "grateful",
    stressed = "stressed"
}
export enum Order {
    less = "less",
    equal = "equal",
    greater = "greater"
}
export interface backendInterface {
    addBookmark(bookName: string, chapterNumber: bigint, verseNumber: bigint, verseText: string): Promise<void>;
    addCheckIn(mood: MoodLabel, note: string | null): Promise<void>;
    compareByTime(a: bigint, b: bigint): Promise<Order>;
    compareText(a: string, b: string): Promise<Order>;
    compareTime(a: bigint, b: bigint): Promise<Order>;
    getBookmarks(): Promise<Array<BibleBookmark>>;
    getCheckInHistory(): Promise<Array<CheckIn>>;
    getLatestCheckIn(): Promise<CheckIn | null>;
    getPreferences(): Promise<UserPreferences>;
    getSavedPrayers(): Promise<Array<SavedPrayer>>;
    removeBookmark(bookName: string, chapterNumber: bigint, verseNumber: bigint): Promise<void>;
    removeSavedPrayer(prayerId: string): Promise<void>;
    savePrayer(prayerId: string, prayerTitle: string, category: string): Promise<void>;
    updatePreferences(preferredTranslation: BibleTranslation, notificationsEnabled: boolean, displayName: string): Promise<void>;
}
import type { BibleTranslation as _BibleTranslation, CheckIn as _CheckIn, MoodLabel as _MoodLabel, Order as _Order, Time as _Time, UserPreferences as _UserPreferences } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBookmark(arg0: string, arg1: bigint, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBookmark(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBookmark(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addCheckIn(arg0: MoodLabel, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCheckIn(to_candid_MoodLabel_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCheckIn(to_candid_MoodLabel_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async compareByTime(arg0: bigint, arg1: bigint): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.compareByTime(arg0, arg1);
                return from_candid_Order_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.compareByTime(arg0, arg1);
            return from_candid_Order_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async compareText(arg0: string, arg1: string): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.compareText(arg0, arg1);
                return from_candid_Order_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.compareText(arg0, arg1);
            return from_candid_Order_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async compareTime(arg0: bigint, arg1: bigint): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.compareTime(arg0, arg1);
                return from_candid_Order_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.compareTime(arg0, arg1);
            return from_candid_Order_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookmarks(): Promise<Array<BibleBookmark>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookmarks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookmarks();
            return result;
        }
    }
    async getCheckInHistory(): Promise<Array<CheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckInHistory();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckInHistory();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestCheckIn(): Promise<CheckIn | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestCheckIn();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestCheckIn();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPreferences(): Promise<UserPreferences> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreferences();
                return from_candid_UserPreferences_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreferences();
            return from_candid_UserPreferences_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSavedPrayers(): Promise<Array<SavedPrayer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedPrayers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedPrayers();
            return result;
        }
    }
    async removeBookmark(arg0: string, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBookmark(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBookmark(arg0, arg1, arg2);
            return result;
        }
    }
    async removeSavedPrayer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSavedPrayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSavedPrayer(arg0);
            return result;
        }
    }
    async savePrayer(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePrayer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePrayer(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePreferences(arg0: BibleTranslation, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePreferences(to_candid_BibleTranslation_n17(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePreferences(to_candid_BibleTranslation_n17(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
}
function from_candid_BibleTranslation_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BibleTranslation): BibleTranslation {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_CheckIn_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CheckIn): CheckIn {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_MoodLabel_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MoodLabel): MoodLabel {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserPreferences_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPreferences): UserPreferences {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CheckIn]): CheckIn | null {
    return value.length === 0 ? null : from_candid_CheckIn_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notificationsEnabled: boolean;
    displayName: string;
    preferredTranslation: _BibleTranslation;
}): {
    notificationsEnabled: boolean;
    displayName: string;
    preferredTranslation: BibleTranslation;
} {
    return {
        notificationsEnabled: value.notificationsEnabled,
        displayName: value.displayName,
        preferredTranslation: from_candid_BibleTranslation_n15(_uploadFile, _downloadFile, value.preferredTranslation)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mood: _MoodLabel;
    note: [] | [string];
    timestamp: _Time;
}): {
    mood: MoodLabel;
    note?: string;
    timestamp: Time;
} {
    return {
        mood: from_candid_MoodLabel_n9(_uploadFile, _downloadFile, value.mood),
        note: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.note)),
        timestamp: value.timestamp
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sad: null;
} | {
    hopeful: null;
} | {
    anxious: null;
} | {
    grateful: null;
} | {
    stressed: null;
}): MoodLabel {
    return "sad" in value ? MoodLabel.sad : "hopeful" in value ? MoodLabel.hopeful : "anxious" in value ? MoodLabel.anxious : "grateful" in value ? MoodLabel.grateful : "stressed" in value ? MoodLabel.stressed : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    esv: null;
} | {
    kjv: null;
} | {
    niv: null;
}): BibleTranslation {
    return "esv" in value ? BibleTranslation.esv : "kjv" in value ? BibleTranslation.kjv : "niv" in value ? BibleTranslation.niv : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    less: null;
} | {
    equal: null;
} | {
    greater: null;
}): Order {
    return "less" in value ? Order.less : "equal" in value ? Order.equal : "greater" in value ? Order.greater : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CheckIn>): Array<CheckIn> {
    return value.map((x)=>from_candid_CheckIn_n7(_uploadFile, _downloadFile, x));
}
function to_candid_BibleTranslation_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BibleTranslation): _BibleTranslation {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_MoodLabel_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MoodLabel): _MoodLabel {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BibleTranslation): {
    esv: null;
} | {
    kjv: null;
} | {
    niv: null;
} {
    return value == BibleTranslation.esv ? {
        esv: null
    } : value == BibleTranslation.kjv ? {
        kjv: null
    } : value == BibleTranslation.niv ? {
        niv: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MoodLabel): {
    sad: null;
} | {
    hopeful: null;
} | {
    anxious: null;
} | {
    grateful: null;
} | {
    stressed: null;
} {
    return value == MoodLabel.sad ? {
        sad: null
    } : value == MoodLabel.hopeful ? {
        hopeful: null
    } : value == MoodLabel.anxious ? {
        anxious: null
    } : value == MoodLabel.grateful ? {
        grateful: null
    } : value == MoodLabel.stressed ? {
        stressed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
